deploy:qa:
  extends: .qa_set_up_ssh
  stage: deploy
  environment:
    name: QA
    url: $QA_HOST
  only:
    - develop
    - /^release\/.+/
    - master
  script:
    - apt-get update
    - apt-get install rsync -y
    - rsync -rv ./public/* "$QA_USERNAME@$QA_HOST:$QA_DIR"

deploy:prod:
  extends: .prod_set_up_ssh
  stage: deploy
  environment:
    name: Production
    url: $PROD_HOST
  only:
    - master
  script:
    - apt-get update
    - apt-get install rsync -y
    - rsync -rv ./public/* "$PROD_USERNAME@$PROD_HOST:$PROD_DIR"
